-- Presets
vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('n', '<left>', '<cmd>echo "Use h to move!!"<CR>')
vim.keymap.set('n', '<right>', '<cmd>echo "Use l to move!!"<CR>')
vim.keymap.set('n', '<up>', '<cmd>echo "Use k to move!!"<CR>')
vim.keymap.set('n', '<down>', '<cmd>echo "Use j to move!!"<CR>')
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })

-- My rebinds
vim.keymap.set('n', '<leader>^', '<C-^>')

vim.keymap.set('n', 'Y', 'yg$', { desc = '[Y]ank to end of line' })
vim.keymap.set('n', '<C-d>', '<C-d>zz')
vim.keymap.set('n', '<C-u>', '<C-u>zz')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('n', 'N', 'Nzzzv')
vim.keymap.set('x', '<leader>p', '"_dP', { desc = '[P]aste without replacing buffer' })
vim.keymap.set('n', '<leader>y', '"+y', { desc = '[Y]ank to clipboard' })
vim.keymap.set('v', '<leader>y', '"+y', { desc = '[Y]ank to clipboard' })
vim.keymap.set('n', '<leader>Y', '"+Y', { desc = '[Y]ank to clipboard' })
vim.keymap.set('n', '<leader>d', '"_d', { desc = '[D]elete without replacing buffer' })
vim.keymap.set('v', '<leader>d', '"_d', { desc = '[D]elete without replacing buffer' })
vim.keymap.set('i', '<C-c>', 'Esc')
vim.keymap.set('n', 'Q', '<nop>', { desc = 'Disable Q' })
vim.keymap.set('n', '<CMD-v>', 'i<CMD-v><CR>')
vim.keymap.set('v', '<CMD-v>', 's<CMD-v><CR>')
vim.keymap.set('n', '<leader>o', 'o<Esc>k', { desc = '[O]pen new line without entering insert mode' })
vim.keymap.set('n', '<leader>O', 'O<Esc>j', { desc = '[O]pen new line without entering insert mode' })
vim.keymap.set('n', '<leader>vo', 'Vs<Esc>', { desc = '[O]pen new line without entering insert mode' })
vim.keymap.set('v', '<leader>o', 's<Esc>', { desc = '[O]pen new line without entering insert mode' })
vim.keymap.set('n', '<leader><TAB>', 'V>', { desc = 'Insert a tab' })
vim.keymap.set('n', '<leader><BS>', 'V<', { desc = 'Remove a tab' })
vim.keymap.set('v', '<TAB>', '>gv', { desc = 'Insert a tab' })
vim.keymap.set('v', '<BS>', '<gv', { desc = 'Add a tab' })

vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { desc = 'Move the current line down [J]' })
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { desc = 'Move the current line up [K]' })
vim.keymap.set('n', 'J', 'mzJ`z', { desc = 'Append the following line to the end of the current line [J]' })
